---
name: Meta - Sync labels

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Generate Token
      #   uses: tibdex/github-app-token@v1
      #   id: generate-token
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          # token: "${{ steps.generate-token.outputs.token }}"
          token: ${{ secrets.GITHUB_TOKEN }}
