---
name: Meta - Labeler

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    name: Labeler
    runs-on: ubuntu-latest
    steps:

      - name: Labeler
        uses: actions/labeler@v4
        with:
          dot: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yaml
