---
name: Publish to TestPyPI

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version.'
        required: false
        default: '3.11'
        type: string
      requirements:
        description: 'Python dependencies to be installed through pip; if empty, use pyproject.toml through build.'
        required: false
        default: ''
        type: string
      artifact:
        description: 'Name of the package artifact.'
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      PYPI_TOKEN:
        description: "Token for pushing releases to PyPI"
        required: false


jobs:
  deploy:
    name: 🚀 Publish to TestPyPI
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write

    steps:
      - name: 📥 Download artifacts '${{ inputs.artifact }}' from 'Package' job
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}-${{ inputs.python-version }}
          path: dist/

      # - name: 🐍 Setup Python ${{ inputs.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ inputs.python-version }}

      # - name: ⚙ Install dependencies for packaging and release
      #   run: |
      #     python -m pip install -U pip
      #     python -m pip install ${{ inputs.requirements }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        if: inputs.environment == test-pypi
        with:
          # Update to dynamic based on environment
          repository-url: https://test.pypi.org/legacy/
          # user: __token__
          # password: ${{ secrets.PYPI_TOKEN }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        if: inputs.environment == release-pypi

      - name: 🗑️ Delete packaging Artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ inputs.artifact }}-${{ inputs.python-version }}
