name: Lint

on:
  workflow_dispatch:

  # Uncomment when ready
  # push:
  #   branches:
  #     - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python_version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
