name: Python package

on:
  workflow_dispatch:

  # Uncomment when ready
  # push:
  #   branches:
  #     - main

env:
  PKG_NAME: epi_helper

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        # - os: macos-latest
        #   path: ~/Library/Caches/pip
        # - os: windows-latest
        #   path: ~\AppData\Local\pip\Cache
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build wheel bdist twine setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build
        run: |
          python -m build --sdist --wheel --outdir dist/
      - name: Upload artifacts
        if: startsWith(matrix.os, 'ubuntu-latest')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*
